import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import apiClient from '../../services/api';
import {
  FileBarChart, Code2, Wrench, TrendingDown,
  AlertTriangle, CheckCircle, Download, Copy, Check,
  Layers, Clock, BarChart3, Sparkles, ArrowRight
} from 'lucide-react';

function ScoreMeter({ label, score, color }: { label: string; score: number; color: string }) {
  return (
    <div className="space-y-1.5">
      <div className="flex justify-between items-center text-xs">
        <span className="text-zinc-400 font-medium">{label}</span>
        <span className={`font-bold font-mono ${color}`}>{score}%</span>
      </div>
      <div className="w-full bg-zinc-800 h-2 rounded-full overflow-hidden">
        <div
          className={`h-full rounded-full transition-all duration-700 ${
            score >= 80 ? 'bg-gradient-to-r from-emerald-500 to-emerald-400' :
            score >= 65 ? 'bg-gradient-to-r from-amber-500 to-amber-400' :
            'bg-gradient-to-r from-red-500 to-red-400'
          }`}
          style={{ width: `${score}%` }}
        />
      </div>
    </div>
  );
}

export default function RepoCTOReportPage() {
  const { id } = useParams<{ id: string }>();
  const [copied, setCopied] = useState(false);

  const { data: report, isLoading, error } = useQuery({
    queryKey: ['cto-report', id],
    queryFn: async () => {
      const { data } = await apiClient.get(`/collab/report/${id}`);
      return data;
    },
    enabled: !!id,
    staleTime: 60000,
  });

  const handleCopyMarkdown = () => {
    if (report?.report_markdown) {
      navigator.clipboard.writeText(report.report_markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadMarkdown = () => {
    if (!report) return;
    const blob = new Blob([report.report_markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.repository_name}_cto_report.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadHTML = () => {
    if (!report) return;
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${report.repository_name} — CTO Report</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 820px; margin: 60px auto; padding: 0 24px; color: #1a1a1a; }
    h1 { font-size: 2rem; border-bottom: 3px solid #7c3aed; padding-bottom: 12px; }
    h2 { font-size: 1.25rem; color: #7c3aed; margin-top: 32px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th, td { text-align: left; padding: 8px 12px; border: 1px solid #e5e7eb; }
    th { background: #f3f4f6; font-weight: 700; }
    li { margin: 6px 0; }
    .footer { color: #9ca3af; font-size: 0.8rem; margin-top: 60px; border-top: 1px solid #e5e7eb; padding-top: 16px; }
  </style>
</head>
<body>
  <pre style="white-space:pre-wrap;font-family:inherit">${report.report_markdown.replace(/</g, '&lt;')}</pre>
  <div class="footer">Generated by RepoMind AI — repomind-beige.vercel.app</div>
</body>
</html>`;
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.repository_name}_cto_report.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = async () => {
    if (!report) return;
    try {
      const response = await apiClient.get(`/collab/report/${id}/export/pdf`, {
        responseType: 'blob'
      });
      const blob = new Blob([response.data], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${report.repository_name}_cto_report.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Failed to download PDF report", err);
    }
  };

  if (isLoading) {
    return (
      <div className="flex-1 bg-zinc-950 flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="w-10 h-10 border-2 border-violet-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-zinc-500 text-sm">Generating executive intelligence report...</p>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="flex-1 bg-zinc-950 flex items-center justify-center p-6">
        <div className="max-w-md glass-card p-8 border-red-500/20 bg-red-500/5 rounded-2xl text-center">
          <AlertTriangle size={32} className="text-red-400 mx-auto mb-3" />
          <h2 className="text-base font-bold text-zinc-200">Report Generation Failed</h2>
          <p className="text-xs text-zinc-500 mt-2">Could not generate the executive report. Ensure the repository has been indexed.</p>
        </div>
      </div>
    );
  }

  const overallStatus = report.overall_score >= 80 ? 'Healthy' : report.overall_score >= 60 ? 'Needs Attention' : 'Critical';
  const overallColor = report.overall_score >= 80 ? 'text-emerald-400' : report.overall_score >= 60 ? 'text-amber-400' : 'text-red-400';

  return (
    <div className="flex-1 overflow-y-auto bg-zinc-950 text-zinc-100">
      <div className="max-w-5xl mx-auto p-6 md:p-8 space-y-6">

        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-zinc-800/60 pb-5">
          <div>
            <div className="flex items-center gap-2 text-[10px] text-zinc-500 mb-1">
              <Clock size={11} />
              Generated {new Date(report.generated_at).toLocaleString()}
            </div>
            <h1 className="text-xl font-bold flex items-center gap-2">
              <FileBarChart size={20} className="text-violet-400" />
              CTO Executive Report
            </h1>
            <p className="text-xs text-zinc-500 mt-1">
              AI-generated technical health assessment for <strong className="text-zinc-300">{report.repository_name}</strong>
            </p>
          </div>
          <div className="flex gap-2 flex-wrap">
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 px-3 py-2 text-xs text-zinc-400 border border-zinc-800 hover:bg-zinc-800 rounded-xl transition-colors"
            >
              {copied ? <Check size={13} className="text-emerald-400" /> : <Copy size={13} />}
              {copied ? 'Copied!' : 'Copy MD'}
            </button>
            <button
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1.5 px-3 py-2 text-xs text-zinc-400 border border-zinc-800 hover:bg-zinc-800 rounded-xl transition-colors"
            >
              <Download size={13} /> .md
            </button>
            <button
              onClick={handleDownloadHTML}
              className="flex items-center gap-1.5 px-3 py-2 text-xs text-zinc-400 border border-zinc-800 hover:bg-zinc-800 rounded-xl transition-colors"
            >
              <Download size={13} /> Export HTML
            </button>
            <button
              onClick={handleDownloadPDF}
              className="flex items-center gap-1.5 px-3 py-2 text-xs bg-violet-600 hover:bg-violet-500 text-white font-bold rounded-xl transition-colors"
            >
              <Download size={13} /> Export PDF
            </button>
          </div>
        </div>

        {/* Overall Health Banner */}
        <div className={`rounded-2xl border p-6 flex flex-col sm:flex-row items-start sm:items-center gap-4 ${
          report.overall_score >= 80
            ? 'border-emerald-500/20 bg-emerald-500/5'
            : report.overall_score >= 60
            ? 'border-amber-500/20 bg-amber-500/5'
            : 'border-red-500/20 bg-red-500/5'
        }`}>
          <div className="flex-1">
            <div className="text-[10px] font-bold uppercase tracking-widest text-zinc-500 mb-1">Overall Codebase Health</div>
            <div className={`text-5xl font-extrabold font-mono ${overallColor}`}>{report.overall_score}%</div>
            <div className={`text-sm font-bold mt-1 ${overallColor}`}>{overallStatus}</div>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            {[
              { label: 'Files', value: report.total_files.toLocaleString(), icon: <Layers size={13} className="text-violet-400" /> },
              { label: 'LOC', value: report.total_loc.toLocaleString(), icon: <Code2 size={13} className="text-cyan-400" /> },
              { label: 'Findings', value: report.total_findings, icon: <AlertTriangle size={13} className="text-amber-400" /> },
              { label: 'Debt (hrs)', value: `${report.tech_debt_hours.toFixed(0)}h`, icon: <Wrench size={13} className="text-red-400" /> },
            ].map((s) => (
              <div key={s.label} className="glass-card border border-zinc-800/60 rounded-xl p-3 text-center">
                <div className="flex justify-center mb-1">{s.icon}</div>
                <div className="text-base font-extrabold font-mono text-zinc-200">{s.value}</div>
                <div className="text-[10px] text-zinc-500 font-medium">{s.label}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Score Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Radar Scores */}
          <div className="glass-card border border-zinc-850 rounded-2xl p-5 space-y-4">
            <h2 className="text-xs font-bold uppercase tracking-wider text-zinc-400 flex items-center gap-2">
              <BarChart3 size={14} className="text-violet-400" /> Quality Dimensions
            </h2>
            <ScoreMeter label="Security Posture" score={report.security_score} color={report.security_score >= 80 ? 'text-emerald-400' : report.security_score >= 60 ? 'text-amber-400' : 'text-red-400'} />
            <ScoreMeter label="Code Quality" score={report.quality_score} color={report.quality_score >= 80 ? 'text-emerald-400' : report.quality_score >= 60 ? 'text-amber-400' : 'text-red-400'} />
            <ScoreMeter label="Architecture" score={report.architecture_score} color={report.architecture_score >= 80 ? 'text-emerald-400' : report.architecture_score >= 60 ? 'text-amber-400' : 'text-red-400'} />
            <ScoreMeter label="Performance" score={report.performance_score} color={report.performance_score >= 80 ? 'text-emerald-400' : report.performance_score >= 60 ? 'text-amber-400' : 'text-red-400'} />
            <ScoreMeter label="Maintainability" score={report.maintainability_score} color={report.maintainability_score >= 80 ? 'text-emerald-400' : report.maintainability_score >= 60 ? 'text-amber-400' : 'text-red-400'} />
          </div>

          {/* Technical Debt */}
          <div className="glass-card border border-zinc-850 rounded-2xl p-5 space-y-4">
            <h2 className="text-xs font-bold uppercase tracking-wider text-zinc-400 flex items-center gap-2">
              <TrendingDown size={14} className="text-amber-400" /> Technical Debt
            </h2>
            <div className="grid grid-cols-2 gap-3">
              {[
                { label: 'Debt Estimate', value: `${report.tech_debt_hours.toFixed(0)} hours`, color: 'text-amber-400' },
                { label: 'Effort Required', value: report.engineering_effort, color: report.engineering_effort === 'Low' ? 'text-emerald-400' : report.engineering_effort === 'Medium' ? 'text-amber-400' : 'text-red-400' },
                { label: 'Critical Issues', value: report.critical_findings, color: report.critical_findings > 0 ? 'text-red-400' : 'text-emerald-400' },
                { label: 'High Severity', value: report.high_findings, color: report.high_findings > 2 ? 'text-amber-400' : 'text-zinc-300' },
              ].map(s => (
                <div key={s.label} className="bg-zinc-900/60 border border-zinc-800/60 rounded-xl p-3">
                  <div className="text-[10px] text-zinc-500 font-medium">{s.label}</div>
                  <div className={`text-lg font-extrabold font-mono mt-1 ${s.color}`}>{s.value}</div>
                </div>
              ))}
            </div>
            <div className="text-[10px] text-zinc-500 leading-relaxed bg-zinc-900/40 border border-zinc-800/40 rounded-lg p-3">
              <strong className="text-zinc-400">Language:</strong> {report.primary_language || 'Mixed'} &nbsp;|&nbsp;
              <strong className="text-zinc-400">Saved Insights:</strong> {report.saved_insights_count} &nbsp;|&nbsp;
              <strong className="text-zinc-400">Notes:</strong> {report.notes_count}
            </div>
          </div>
        </div>

        {/* Top Risks */}
        <div className="glass-card border border-red-500/10 rounded-2xl p-5 space-y-3 bg-red-500/5">
          <h2 className="text-xs font-bold uppercase tracking-wider text-red-400 flex items-center gap-2">
            <AlertTriangle size={14} /> Top Risks
          </h2>
          <div className="space-y-2">
            {report.top_risks.map((risk: string, i: number) => (
              <div key={i} className="flex items-start gap-2.5 text-xs text-zinc-300">
                <span className="w-5 h-5 rounded-full bg-red-500/10 border border-red-500/20 text-red-400 font-bold text-[10px] flex items-center justify-center shrink-0 mt-0.5">
                  {i + 1}
                </span>
                {risk}
              </div>
            ))}
          </div>
        </div>

        {/* Recommended Actions */}
        <div className="glass-card border border-emerald-500/10 rounded-2xl p-5 space-y-3 bg-emerald-500/5">
          <h2 className="text-xs font-bold uppercase tracking-wider text-emerald-400 flex items-center gap-2">
            <CheckCircle size={14} /> Recommended Actions
          </h2>
          <div className="space-y-2">
            {report.recommended_actions.map((action: string, i: number) => (
              <div key={i} className="flex items-start gap-2.5 text-xs text-zinc-300">
                <ArrowRight size={13} className="text-emerald-400 shrink-0 mt-0.5" />
                {action}
              </div>
            ))}
          </div>
        </div>

        {/* Markdown Raw Export Preview */}
        <div className="glass-card border border-zinc-800 rounded-2xl p-5 space-y-3">
          <div className="flex items-center justify-between">
            <h2 className="text-xs font-bold uppercase tracking-wider text-zinc-400 flex items-center gap-2">
              <Sparkles size={13} className="text-violet-400" /> Report Markdown
            </h2>
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1 text-[10px] text-zinc-500 hover:text-zinc-300 transition-colors"
            >
              {copied ? <Check size={11} className="text-emerald-400" /> : <Copy size={11} />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="text-[10px] font-mono text-zinc-500 bg-zinc-900/60 border border-zinc-800/60 rounded-xl p-4 overflow-x-auto max-h-64 whitespace-pre-wrap leading-relaxed">
            {report.report_markdown}
          </pre>
        </div>

        <div className="text-center text-[10px] text-zinc-600 pb-4">
          Report generated by RepoMind AI · {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  );
}
